$HOME/.config/kitty/theme.conf|killall -SIGUSR1 kitty

## name:     Purple Dark
## author:   Custom

# The basic colors
foreground              #E0E0E0
background              #0D0D0D
selection_foreground    #0D0D0D
selection_background    #A855F7

# Cursor colors
cursor                  #A855F7
cursor_text_color       #0D0D0D

# URL underline color when hovering with mouse
url_color               #A855F7

# Kitty window border colors
active_border_color     #A855F7
inactive_border_color   #1A1A1A
bell_border_color       #EC4899

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #0D0D0D
active_tab_background   #A855F7
inactive_tab_foreground #E0E0E0
inactive_tab_background #121212
tab_bar_background      #0D0D0D

# Colors for marks (marked text in the terminal)
mark1_foreground #0D0D0D
mark1_background #A855F7
mark2_foreground #0D0D0D
mark2_background #7C3AED
mark3_foreground #0D0D0D
mark3_background #EC4899

# The 16 terminal colors

# black
color0 #1A1A1A
color8 #222222

# red
color1 #F85149
color9 #F85149

# green
color2  #3FB950
color10 #3FB950

# yellow
color3  #D29922
color11 #D29922

# blue
color4  #A855F7
color12 #A855F7

# magenta
color5  #EC4899
color13 #EC4899

# cyan
color6  #3FB950
color14 #3FB950

# white
color7  #E0E0E0
color15 #808080
